### ISSUE TITLE
Funding Request: Holesky Faucet Request for Grant by Automata Network 

### ISSUE THREAD

**Issue by teye** [ethpandaops/fundingvault#25]
### Project Name

Holesky Faucet

### Whats the link to your project?

https://www.holeskyfaucet.io

### Is this a one-time request or do you need an ongoing funding?

Ongoing Funding (monthly)

### What amount of funds do you need?

60000

### What do you need these funds for?

Our team at Automata Network has developed a holesky faucet that has built-in sybil resistance mechanism. Using our Proof of Machinehood, users only need to enter their wallet address and attest their device to receive the testnet tokens. All of this is done without the users having to connect their wallets or signing any transaction messages. We are requesting the funds for Holesky Faucet as the demand for the tokens have been increasing rapidly. To ensure the continuation of the project and benefiting the community, a steady stream of funds is essential.

### Which testnet do you need funds on?

Holesky

### Wallet Address

0x12739FAfA03d97724eb37b53CC2874C01C43F5FD (ENS: deligong.eth)

### Verification

https://www.holeskyfaucet.io

### Code of Conduct

- [X] I agree that I will not sell testnet funds for money in any way.
- [X] I agree that I will not hoard testnet funds with no actual need.

**Comment by pk910** [comment]
Thanks for your service :)
application for records, already granted.
