### ISSUE TITLE
Funding Request: Sepolia Faucet Request - QuickNode Faucet

### ISSUE THREAD

**Issue by zer0cache** [ethpandaops/fundingvault#29]
### Project Name

QuickNode Faucet

### Whats the link to your project?

https://faucet.quicknode.com/ethereum/sepolia

### Is this a one-time request or do you need an ongoing funding?

Ongoing Funding (monthly)

### What amount of funds do you need?

10000

### What do you need these funds for?

We process around ~90k drips of Sepolia on our faucet per month for a drip amount of .05 to .1 ETH. This sometimes goes as high to 150k/mo (7.5k - 15k ETH worth), but on average we do about 90-100k drips/month. This is across all testnet chains that we support with Sepolia. 

We'll be using the funds to fund the faucet on the continuous basis for Sepolia on Ethereum and EVM testnets that support Sepolia. 

You can view the current activity of the Ethereum Sepolia faucet at https://sepolia.etherscan.io/address/0x2CdA41645F2dBffB852a605E92B185501801FC28 . 

Happy to provide the address for other chain testnets leveraging Sepolia on our faucet if needed!

### Which testnet do you need funds on?

Sepolia

### Wallet Address

0x2CdA41645F2dBffB852a605E92B185501801FC28

### Verification

https://faucet.quicknode.com

### Code of Conduct

- [X] I agree that I will not sell testnet funds for money in any way.
- [X] I agree that I will not hoard testnet funds with no actual need.

**Comment by pk910** [comment]
DNS Record verified & matches address 👍
Looks all good, so granted 10k SepETH/Month as requested :)
If you need an adjustment, please re-open this issue.

Thank you for running your faucets.

**Comment by zer0cache** [comment]
hey @pk910, we're looking for an adjustment if possible. Below is the related info:

------

Project Name
QuickNode Faucet & QuickNode Rollups as a service (testnet faucets for these rollups)

Whats the link to your project?
https://faucet.quicknode.com/ethereum/sepolia
https://www.quicknode.com/rollup

Is this a one-time request or do you need an ongoing funding?
Ongoing Funding (monthly)

What amount of funds do you need?
100000

What do you need these funds for?
**QuickNode Faucet**
We process around ~90k drips of Sepolia on our faucet per month for a drip amount of .05 to .1 ETH. This sometimes goes as high to 150k/mo (7.5k - 15k ETH worth), but on average we do about 90-100k drips/month. This is across all testnet chains that we support with Sepolia.

We'll be using the funds to fund the faucet on the continuous basis for Sepolia on Ethereum and EVM testnets that support Sepolia.

You can view the current activity of the Ethereum Sepolia faucet at https://sepolia.etherscan.io/address/0x2CdA41645F2dBffB852a605E92B185501801FC28 .

Happy to provide the address for other chain testnets leveraging Sepolia on our faucet if needed!

**QuickNode Rollup as a service Faucets**
We're rolling out the ability to deploy rollups on testnets along with a faucet to accompany the rollup. Given Sepolia gas prices, we're spending 100 eth on deployment alone. This does not include funds added to the rollup's faucet, which we project to be similar in usage to the QuickNode faucet.

Which testnet do you need funds on?
Sepolia

Wallet Address
0x2CdA41645F2dBffB852a605E92B185501801FC28

Verification
https://faucet.quicknode.com/

Code of Conduct
[x] I agree that I will not sell testnet funds for money in any way.
[x] I agree that I will not hoard testnet funds with no actual need.
