### ISSUE TITLE
Funding Request: Alchemy

### ISSUE THREAD

**Issue by elanh** [ethpandaops/fundingvault#31]
### Project Name

Alchemy Faucets

### Whats the link to your project?

https://www.alchemy.com/faucets/ethereum-sepolia

### Is this a one-time request or do you need an ongoing funding?

Ongoing Funding (monthly)

### What amount of funds do you need?

50k (but ideally 100k or more per month)

### What do you need these funds for?

We run faucets for the community and get ~100k monthly users. 

We need both Sepolia and Holesky test eth to fund our faucets. 

### Which testnet do you need funds on?

Sepolia

### Wallet Address

0xD8Ea779b8FFC1096CA422D40588C4c0641709890

### Verification

Will confirm legitimacy in the Eth Foundation + Alchemy telegram group

### Code of Conduct

- [X] I agree that I will not sell testnet funds for money in any way.
- [X] I agree that I will not hoard testnet funds with no actual need.

**Comment by pk910** [comment]
Heya @elanh,

All good from my side as you're a reliable faucet provider for years :)
Verified address via TG group and added a grant for 100k ETH/month on sepolia as requested.

If you need an adjustment, please re-open this issue.
Please also open another issue for the holesky request.

Thanks for providing your services!
