### ISSUE TITLE
Funding Request: <title>

### ISSUE THREAD

**Issue by LeoObol** [ethpandaops/fundingvault#32]
### Project Name

Obol Collective - Techne Credential Program

### Whats the link to your project?

https://squadstaking.com/techne

### Is this a one-time request or do you need an ongoing funding?

One-Time Drop

### What amount of funds do you need?

650k 

### What do you need these funds for?

The Techne Credential Program by Obol is designed to educate and empower participants in mastering distributed validators (DVs) within the Ethereum staking ecosystem. As part of the program's hands-on phase, participants will configure, run, and successfully manage distributed validator clusters. To facilitate this, we will deposit the required ETH for all applicants and activate their clusters. 

To achieve this, we require substantial Holesky ETH to ensure seamless operation and activation of these clusters. This grant will allow us to provide the necessary resources for participants to gain practical experience, thereby fostering a robust and knowledgeable validator community. 
The reason why we require a significant amount of Holesky ETH is that each cluster of participants needs to deploy 50 validator keys and run them for a month. This scale is necessary to accurately track the block proposal success rate, given that these events occur infrequently. A higher number of validator keys increases the likelihood of obtaining a representative success rate.

In the last wave, we activated 400 clusters, which would now require over 600k Holesky ETH. During the last wave they were only required to deploy a single validator. This grant will be a one-time request as participants are required to return the ETH programmatically, ensuring the funds are recycled for future use. 

This initiative aligns with the Ethereum Foundation's mission to advance the ecosystem by providing educational and practical opportunities for community members. By funding this program, we will enhance the scalability and reliability of Ethereum's infrastructure through a well-trained network of distributed validators.

### Which testnet do you need funds on?

Holesky

### Wallet Address

0xC8D0f262197DbAD9DF8245E2E70a61349343Ba56

### Verification

Domain: squadstaking.com Name: holesky_funding Value: 0xC8D0f262197DbAD9DF8245E2E70a61349343Ba56

### Code of Conduct

- [X] I agree that I will not sell testnet funds for money in any way.
- [X] I agree that I will not hoard testnet funds with no actual need.

**Comment by pk910** [comment]
Heya @LeoObol 

Thanks for your request, looks all good.
The requested amount sums up to roughly 20k validator, which is reasonable for a project of your size :)

I've sent the requested amount to the specified wallet.

**Comment by LeoObol** [comment]
Hey @pk910, 

Thanks a lot for the quick follow up, we really appreciate the support ! 

Holesky ETH well received, thank you !
