### ISSUE TITLE
Funding Request: Zircuit testnet

### ISSUE THREAD

**Issue by bearpebble** [ethpandaops/fundingvault#33]
### Project Name

Zircuit

### Whats the link to your project?

https://www.zircuit.com/

### Is this a one-time request or do you need an ongoing funding?

Ongoing Funding (monthly)

### What amount of funds do you need?

20k

### What do you need these funds for?

We are running testnets for our rollup and spend most of the eth on blobs for data availability. The main spenders are the two batcher addresses
- https://sepolia.etherscan.io/address/0xa07FA473B87D7ADee161f458aF300255B65F33f6
- https://sepolia.etherscan.io/address/0xe59C24676fBF48f2b3F52dbF4D4938610378B081

Testnet docs: https://docs.zircuit.com/testnet/quick-start

### Which testnet do you need funds on?

Sepolia

### Wallet Address

0xEd24503c5718B4690E15062b1bEb9ff7f4ccc23f

### Verification

Added DNS TXT record to zircuit.com

### Code of Conduct

- [X] I agree that I will not sell testnet funds for money in any way.
- [X] I agree that I will not hoard testnet funds with no actual need.

**Comment by pk910** [comment]
Heya @bearpebble 

Thanks for your request.
I've checked the DNS record, which matches the provided address 👍
Looks all good, so granted 20k SepETH/Month as requested :)
You should be able to claim those via the UI now: https://fundingvault.ethpandaops.io/

If you need an adjustment, please re-open this issue.
