### ISSUE TITLE
Funding Request: <title>Request sepolia amount

### ISSUE THREAD

**Issue by aamirkahan** [ethpandaops/fundingvault#34]
### Project Name

Blocky Rocks

### Whats the link to your project?

https://www.blocky.rocks/delphi-oracle

### Is this a one-time request or do you need an ongoing funding?

Ongoing Funding (monthly)

### What amount of funds do you need?

5k

### What do you need these funds for?

We are building Delphi, a groundbreaking zero knowledge proof based EVM oracle system. I’m requesting 5k Sepolia Eth to help us test our zkp onchain contracts. The Sepolia Eth will be used by our developers to test the EVM components of our product. This amount of Eth will enable our developers to move more quickly towards our launch as we have hit a bottleneck on what faucets can provide.

### Which testnet do you need funds on?

Sepolia

### Wallet Address

0x2EA8206867ccE5BaFC438641b853BBE1b20D1d62

### Verification

0x6801a745bd61B3F28962203538ecd3171E1Ab7B9 https://www.blocky.rocks/

### Code of Conduct

- [X] I agree that I will not sell testnet funds for money in any way.
- [X] I agree that I will not hoard testnet funds with no actual need.

**Comment by pk910** [comment]
Heya @aamirkahan,

Can you give us some more details about what you need an ongoing amount of funds for?
For contract testing, the amount usually doesn't matter too much, so the amounts provided by faucets should be enough for deployment & testing tasks.

I also can't verify the integrity of your request. There's no TXT record behind `www.blocky.rocks` that points to one of your provided addresses, nor can I find the address on your website.
