### ISSUE TITLE
Funding Request: Sepolia Faucet Request - QuickNode Faucet & QuickNode Rollups as a Service

### ISSUE THREAD

**Issue by zer0cache** [ethpandaops/fundingvault#35]
### Project Name

QuickNode Faucet & QuickNode Rollup Faucets

### Whats the link to your project?

https://faucet.quicknode.com/ethereum/sepolia

### Is this a one-time request or do you need an ongoing funding?

Ongoing Funding (monthly)

### What amount of funds do you need?

50000

### What do you need these funds for?

We are asking to increase the funding from our previous ask, which can be found [here](https://github.com/ethpandaops/fundingvault/issues/29). This request is for an additional 40,000 Sepolia monthly to accommodate Faucets for rollups we are deploying on Sepolia. 50,000 is quoted as the total fund amount needed to include the current 10,000 monthly allocation we have. Please let me know if this should be updated to include only total _new_ funding.

**QuickNode Rollup Faucets** - 40k/mo
We're rolling out the ability to deploy rollups on testnets along with a faucet to accompany the rollup. Given Sepolia gas prices, we're spending about 100 sepolia ETH on each deployment. This does not include funds added to the rollup's faucet, which we project to be similar or moderately less in usage to the QuickNode faucet per each instance that we deploy. We are asking for 40k sepolia monthly to accommodate for these deployments and funding of the faucets for these roll ups.

The [previous funding request](https://github.com/ethpandaops/fundingvault/issues/29) was approved for the QuickNode faucet for 10k Sepolia monthly - I am pasting the contents from that request below to consolidate our asks into one issue.

**QuickNode Faucet** - 10k/mo
We process around ~90k drips of Sepolia on our faucet per month for a drip amount of .05 to .1 ETH. This sometimes goes as high to 150k/mo (7.5k - 15k ETH worth), but on average we do about 90-100k drips/month. This is across all testnet chains that we support with Sepolia.

We'll be using the funds to fund the faucet on the continuous basis for Sepolia on Ethereum and EVM testnets that support Sepolia.

You can view the current activity of the Ethereum Sepolia faucet at https://sepolia.etherscan.io/address/0x2CdA41645F2dBffB852a605E92B185501801FC28 .

Happy to provide the address for other chain testnets leveraging Sepolia on our faucet if needed!

Thank you for your consideration!

### Which testnet do you need funds on?

Sepolia

### Wallet Address

0x2CdA41645F2dBffB852a605E92B185501801FC28

### Verification

https://faucet.quicknode.com

### Code of Conduct

- [X] I agree that I will not sell testnet funds for money in any way.
- [X] I agree that I will not hoard testnet funds with no actual need.

**Comment by pk910** [comment]
yup, sounds good :)
I've adjusted the grant amount 👍

**Comment by zer0cache** [comment]
Thank you @pk910 ! We appreciate ya'll :)
