### ISSUE TITLE
Funding Request: Rubyscore

### ISSUE THREAD

**Issue by rubyscore-tech** [ethpandaops/fundingvault#36]
### Project Name

Rubyscore.io

### Whats the link to your project?

https://rubyscore.io/

### Is this a one-time request or do you need an ongoing funding?

Ongoing Funding (monthly)

### What amount of funds do you need?

50000

### What do you need these funds for?

RubyScore is an infrastructural solution for showing the statistics of networks and wallet and building a ranking, for the convenience of users we build our own faucet that their ranking when testing certain projects also built in the test network, as well as it is a great convenience for developers and for ordinary users of the project.
Test ETH can be obtained in two ways
1. By reposting a tweet (X post) + subscription to rubyscore Twitter(X) account
2. Through on-chain activity in networks, if the user can make mint for NFT boxes, he will be able to claim test ETH + cloudfare
In order to have NFT boxes he needs to show great on-chain activity.
The prototype like shows the almost finished design of the work
https://dev-fe.rubyscore.io/faucet

### Which testnet do you need funds on?

Sepolia

### Wallet Address

0xe3c06d666471df173a857399276b6c2b869ba0d9

### Verification

https://rubyscore.io

### Code of Conduct

- [X] I agree that I will not sell testnet funds for money in any way.
- [X] I agree that I will not hoard testnet funds with no actual need.

**Comment by pk910** [comment]
Heya @rubyscore-tech

I've checked the TXT record and tried the dev faucet, works fine :)

Granted 5k/Month for now, please reopen or reply to this issue if you need a raise.
see https://github.com/ethpandaops/fundingvault/issues/37#issuecomment-2386355595
