### ISSUE TITLE
Funding Request: Skate

### ISSUE THREAD

**Issue by Skate-github** [ethpandaops/fundingvault#39]
### Project Name

Skate

### Whats the link to your project?

https://www.skatechain.org/

### Is this a one-time request or do you need an ongoing funding?

Ongoing Funding (monthly)

### What amount of funds do you need?

20,000

### What do you need these funds for?

At Skate, we are building the infrastructure for DApps to interact cross-chains with a single shared state. We are running a testnet L2 and would like to enable the following:

1. A batcher submit to L1 sepolia: [https://sepolia.etherscan.io/txs?a=0x73c076b1008323c76f8aa7acd82cdbd0e854fd23](https://sepolia.etherscan.io/txs?a=0x73c076b1008323c76f8aa7acd82cdbd0e854fd23). This consume ~10k ETH per month, including some unusual time where base gas price spike on Sepolia:
![Screenshot from 2024-10-07 12-25-27](https://github.com/user-attachments/assets/c21cf856-c6b1-4ed1-9c28-8ec71bbb4246)

2. Gasless transaction for user to interact with our campaign: https://park.skatechain.org/en/nft. We currently have ~3M mints. Which will consume bridged Sepolia gas on our chain and all other supported Sepolia-ETH testnet. Which currently at ~10k ETH per month.

Skatechain docs: [https://docs.skatechain.org](https://docs.skatechain.org)

### Which testnet do you need funds on?

Sepolia

### Wallet Address

0xBBE307DB73D8fD981A7dAB929E2a41225CF0658A

### Verification

https://mxtoolbox.com/SuperTool.aspx?action=txt%3afunding.skatechain.org

### Code of Conduct

- [x] I agree that I will not sell testnet funds for money in any way.
- [X] I agree that I will not hoard testnet funds with no actual need.

**Comment by pk910** [comment]
Heya @Skate-github,

Tanks for your request.
I've verified the address & link, looks all good.

We're fine with providing the funding for running the batcher for your L2 chain (10k/month), 
but we're a bit worried about the gasless transactions as providing gas is kind of a limiting factor for on chain activity (as we don't have the financial factor).
Are you fine with a funding of 10k SepETH/month for your batcher?

**Comment by Skate-github** [comment]
The $10k/month for the batcher works for us. 
--
Gasless mints are currently handled by a set of executors, which are EOAs. The user is required to sign the execution calldata. To prevent bots, we have captcha implemented on the Frontend and certain actions are restricted to signed-in Twitter users.

**Comment by pk910** [comment]
I've created a grant for 15k/month :)
You should be able to claim those via the UI (https://fundingvault.ethpandaops.io/) now.

Please reply to this issue or create another one if you need an adjustment :)
