### ISSUE TITLE
Funding Request: Google (Sepolia)

### ISSUE THREAD

**Issue by DevanM** [ethpandaops/fundingvault#40]
### Project Name

Google Cloud Web3, Public Faucet - Sepolia

### Whats the link to your project?

https://cloud.google.com/application/web3/faucet/ethereum/sepolia

### Is this a one-time request or do you need an ongoing funding?

Recurring funding

### What amount of funds do you need?

400000 (or 100k recurring )

### What do you need these funds for?

Google Web3 is excited to host a public faucet for developers, students, researchers, and startups learning and building on Ethereum. 

This request is to top-up funds for our public Sepolia faucet located at the same address as our initial drip. Thanks!

### Which testnet do you need funds on?

Sepolia

### Wallet Address

0x7af13Cf7D746d5bC33BCd51c3D4A9261a477103C

### Verification

https://cloud.google.com/application/web3/faucet/ethereum/sepolia

### Code of Conduct

- [X] I agree that I will not sell testnet funds for money in any way.
- [X] I agree that I will not hoard testnet funds with no actual need.

**Comment by pk910** [comment]
Heya @DevanM 
Thanks for your request.
Address & url looks valid, thanks for providing your faucet service :)

According to your wallet, you're currently distributing about 10-20k per month, 
so a funding of 100k/Month seems a bit overkill ;)
Are you fine with a 25k/Month allocation?

**Comment by DevanM** [comment]
@pk910 Perfect, lets start with 25k/month and go from there. Thanks!

**Comment by pk910** [comment]
I've added you to the contract with 25k/Month :)
You should be able to claim it via the UI now: https://fundingvault.ethpandaops.io/

Please reply to this issue or create another one if you need an adjustment :)

**Comment by DevanM** [comment]
gm @pk910 we're unable to claim through my previously provided address. 

Ask: Can you instead approve the recurring drip for **0xfc7AF49b80ACF041744366B02272019723C94F9c**

You can disregard the previous address.

Thanks!

**Comment by pk910** [comment]
Heya @DevanM,
I've moved the grant to `0xfc7AF49b80ACF041744366B02272019723C94F9c` as requested :)
Please let me know if that works for you or if there is some other issue with the UI?

**Comment by DevanM** [comment]
hey @pk910 excellent, the claim worked perfectly. We'll use this portal for recurring drips going forward. Appreciate the assistance 🙏🏻

**Comment by seaneganx** [comment]
@pk910 is it possible to increase our allowance to 50,000? Our current disbursement rate is 1,300 per day, or roughly 30,000 over the past month, and our traffic continues to increase month over month.

**Comment by pk910** [comment]
Heya @seaneganx,
I've increased the allowance to 50k/Month as requested :)

**Comment by seaneganx** [comment]
Hey @pk910 our faucet is running dangerously low on funds. Our faucet disbursement has increased steadily up to 2,000 per day before ETH Denver, and right now we're seeing over 3,000 per day.

Can we increase to 80,000/month allowance? That should be a sustainable amount for the next couple months assuming traffic decreases after ETH Denver. And can we also get a one-time grant of 100,000?

Right now we're claiming our allowance weekly and rationing the claim across our faucet accounts so they don't run out. Having  a one-time grant would let us give the faucet accounts more runway.

Thanks,
Sean

**Comment by pk910** [comment]
Heya @seaneganx
Sorry, for the delay 😅
I've been checking it like a week ago and also got an internal approval, but actually missed updating the grant.
This is now done :) So you have an allowance of 100k/month now.
