### ISSUE TITLE
Funding Request: INFINIT Holesky Faucet

### ISSUE THREAD

**Issue by arintrongs** [ethpandaops/fundingvault#41]
### Project Name

INFINIT

### Whats the link to your project?

https://faucet.infinit.tech

### Is this a one-time request or do you need an ongoing funding?

One-Time Drop

### What amount of funds do you need?

10000

### What do you need these funds for?

We are operating a Holesky Testnet Faucet as part of the INFINIT stack to enhance the experience for DeFi developers in building and testing protocols. 

Our faucet was recently launched, and we are requesting a one-time token drop to determine an optimal amount for ongoing faucet operations. 

### Which testnet do you need funds on?

Holesky

### Wallet Address

0x4cb358a50c35da2a418a8ad1b958d761835ffa76

### Verification

faucet.infinit.tech

### Code of Conduct

- [X] I agree that I will not sell testnet funds for money in any way.
- [X] I agree that I will not hoard testnet funds with no actual need.

**Comment by pk910** [comment]
Heya @arintrongs 

I've verified the address & link, looks good :)
A 10k request for getting things started sounds good 👍
