### ISSUE TITLE
Funding Request: Request for holesky eth needed for testing Obol products

### ISSUE THREAD

**Issue by st1p3-obol** [ethpandaops/fundingvault#42]
### Project Name

Obol (DV Labs) 

### Whats the link to your project?

https://holesky.launchpad.obol.tech/

### Is this a one-time request or do you need an ongoing funding?

Ongoing Funding (monthly)

### What amount of funds do you need?

30000

### What do you need these funds for?

At Obol I am one of the QAs who work on testing. Concretely these funds would be used to test validator deposits of the newly created charon clusters. 
My goal is to also exit properly at the end of testing so these funds are not used one-time

### Which testnet do you need funds on?

Holesky

### Wallet Address

0x44772a9B42e7E0a7fD29f293Bf9E569a88A608D5

### Verification

Domain: squadstaking.com Name: stipe_holesky_funding Value: 0x44772a9B42e7E0a7fD29f293Bf9E569a88A608D5

### Code of Conduct

- [X] I agree that I will not sell testnet funds for money in any way.
- [X] I agree that I will not hoard testnet funds with no actual need.

**Comment by pk910** [comment]
Heya @st1p3-obol,
Sorry for the delay, I've checked the verification, all good :)
I've created a grant for 30k/Month on holesky as requested.
You should be able to claim those via the UI now (https://fundingvault.ethpandaops.io/)
Please reply to this issue or create another one if you need an adjustment.
