### ISSUE TITLE
Funding Request: Chainlink Holesky

### ISSUE THREAD

**Issue by friedemannf** [ethpandaops/fundingvault#43]
### Project Name

Chainlink Labs

### Whats the link to your project?

https://faucets.chain.link/

### Is this a one-time request or do you need an ongoing funding?

Ongoing Funding (monthly)

### What amount of funds do you need?

20k/month

### What do you need these funds for?

We're requesting Holesky ETH to provide ongoing funding for:
- The public faucet at faucet.chain.link
- Keeping the testnet operators for all Chainlink products funded

### Which testnet do you need funds on?

Holesky

### Wallet Address

0x05C720EDB38852673CC3B43D2b59dFDdC16C1Ded

### Verification

TXT record @ fundingvault.chain.link
```
fundingvault.chain.link. 300	IN	TXT	"0x05C720EDB38852673CC3B43D2b59dFDdC16C1Ded"
```

### Code of Conduct

- [X] I agree that I will not sell testnet funds for money in any way.
- [X] I agree that I will not hoard testnet funds with no actual need.

**Comment by friedemannf** [comment]
Hey @pk910 👋
The inital request was for the address that sends all our faucet transactions on all networks. Updated the request to an EOA `0x05C720EDB38852673CC3B43D2b59dFDdC16C1Ded` as well has had a TXT record set for fundingvault.chain.link.
This is probably better anyway as we won't mess with the nonce management of our faucet when interacting with the grant. 
Hope this works, thank you for your support :)

**Comment by parithosh** [comment]
Happy to approve the request as well :)

**Comment by pk910** [comment]
Heya @friedemannf 
I've checked the verification, all good now :)
Created a grant for 20k HolETH/month as requested. You should be able to claim those via the [UI](https://fundingvault.ethpandaops.io/) now.

Please reply to this issue if you need an adjustment :)
