### ISSUE TITLE
Funding Request: Aztec Testnet

### ISSUE THREAD

**Issue by rahul-kothari** [ethpandaops/fundingvault#44]
### Project Name

Aztec

### Whats the link to your project?

https://aztec.network/

### Is this a one-time request or do you need an ongoing funding?

One-Time Drop

### What amount of funds do you need?

15k

### What do you need these funds for?

Aztec is an L2 deploying a public decentralized testnet on Sepolia. We need these funds for our continuous testing, multiple upgrades and versions of the testnet (especially in the early days), our L2 faucet for our public testnet for our users. Since this will be the first time users can try the aztec testnet, we expect a lot of activity. This testnet will exist forever, even post aztec mainnet, hence we are requesting a big amount

### Which testnet do you need funds on?

Sepolia

### Wallet Address

0x33D525f5ac95c2BCf98b644738C7d5673480493A

### Verification

Run `dig TXT aztec.network` in yoru terminal. One of the records should be wallet=0x33D525f5ac95c2BCf98b644738C7d5673480493A

### Code of Conduct

- [X] I agree that I will not sell testnet funds for money in any way.
- [X] I agree that I will not hoard testnet funds with no actual need.

**Comment by pk910** [comment]
Heya @rahul-kothari,

Thanks for your request, I've checked the verification, looks all fine :)
I've sent you the requested amount. Please reply to this issue if you need a top up.

**Comment by rahul-kothari** [comment]
Thanks!

**Comment by rahul-kothari** [comment]
Hi @pk910 

We significantly under estimated how much ETH we needed for our decentralized testnet

Could we get a top up of 100k?
