### ISSUE TITLE
Funding Request: Node Operator

### ISSUE THREAD

**Issue by admsk2** [ethpandaops/fundingvault#7]
### Project Name

Block54 Nodes

### Whats the link to your project?

https://block54.capital

### Is this a one-time request or do you need an ongoing funding?

One-Time Drop

### What amount of funds do you need?

50k

### What do you need these funds for?

We are migrating with Eigenlayer AVS validating node from Goerli to Holesky and in order to validate AVS services (currently EigenDA) it was needed to have at least 35k Goerli ETH. I assume 50k should be sufficient to run a node and validate services on Holesky.
The node I am referring to:
https://goerli.eigenlayer.xyz/operator/0x9f164ef7f03e7400b19a6301b35b7d24020ca77f

### Wallet Address

0x9f164ef7f03e7400b19a6301b35b7d24020ca77f

### Code of Conduct

- [X] I agree that I will not sell testnet funds for money in any way.
- [X] I agree that I will not hoard testnet funds with no actual need.

**Comment by pk910** [comment]
Heya @admsk2,

Thanks for reaching out about getting a 50k HolETH allocation. We really appreciate your patience and want to apologize for the delay in our response. We've been coordinating with the eigenlayer team to ensure we can support former goerli operators in the best way possible, which took a bit of time to finalize.

We understand that making it into the top 200 of the EigenDA AVS is important, especially with the shift from the goerli network. However, we aim to keep things fair for all participants. Distributing large amounts of Holesky ETH for top list positions would mean that we'd have to make decisions about who gets in and who doesn’t. 
We'd prefer to avoid that to maintain a level playing field.

The good news is eigenlayer will distribute HolETH to former goerli operators directly, as we've provided them with a large allocation for this purpose.

Please note, eigenlayer is still working on their Holesky setup. They'll likely share more details once everything is ready.

**Comment by admsk2** [comment]
Hey @pk910,

thanks for the clarification and comprehensive response. I am in touch with eigenlayer team, and it looks like we will sort everything out internally.

Case closed :)
